/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pacoteecono;

/**
 *
 * @author camil
 */
public class PaginaInicial extends javax.swing.JFrame {

    /**
     * Creates new form PaginaInicial
     */
    public PaginaInicial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btn_cambio = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btn_lucro = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btn_demanda = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        btn_Elast = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        btn_ElastC = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        btn_ElastP = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        btn_ElastR = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jLabel1.setText("Software de Economia");

        btn_cambio.setText("Entrar");
        btn_cambio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_cambioMouseClicked(evt);
            }
        });
        btn_cambio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cambioActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Câmbio e Investimentos");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Custo, Receita e Lucro");

        btn_lucro.setText("Entrar");
        btn_lucro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_lucroMouseClicked(evt);
            }
        });
        btn_lucro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_lucroActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Demanda");

        btn_demanda.setText("Entrar");
        btn_demanda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_demandaMouseClicked(evt);
            }
        });
        btn_demanda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_demandaActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Elasticidade");

        btn_Elast.setText("Entrar");
        btn_Elast.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_ElastMouseClicked(evt);
            }
        });
        btn_Elast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ElastActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Elasticidade Cruzada");

        btn_ElastC.setText("Entrar");
        btn_ElastC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_ElastCMouseClicked(evt);
            }
        });
        btn_ElastC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ElastCActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Elasticidade Preço");

        btn_ElastP.setText("Entrar");
        btn_ElastP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_ElastPMouseClicked(evt);
            }
        });
        btn_ElastP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ElastPActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Elasticidade Renda");

        btn_ElastR.setText("Entrar");
        btn_ElastR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_ElastRMouseClicked(evt);
            }
        });
        btn_ElastR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ElastRActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(btn_cambio)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel4)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btn_ElastP)
                                    .addGap(190, 190, 190))
                                .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(btn_ElastR)))
                    .addComponent(btn_ElastC)
                    .addComponent(btn_Elast)
                    .addComponent(btn_demanda)))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(btn_lucro)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_cambio)
                            .addComponent(btn_demanda)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_lucro))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_Elast)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_ElastC)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_ElastP)
                .addGap(16, 16, 16)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_ElastR)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_cambioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_cambioMouseClicked
         Frm_cambio frm_cambio = new Frm_cambio();
         frm_cambio.setVisible(true);
         this.dispose();
    }//GEN-LAST:event_btn_cambioMouseClicked

    private void btn_cambioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cambioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_cambioActionPerformed

    private void btn_lucroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_lucroMouseClicked
         Frm_Lucro frm_Lucro = new Frm_Lucro();
         frm_Lucro.setVisible(true);
         this.dispose();
    }//GEN-LAST:event_btn_lucroMouseClicked

    private void btn_lucroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_lucroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_lucroActionPerformed

    private void btn_ElastMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ElastMouseClicked
        // TODO add your handling code here:
         Frm_elasticidade frm_elasticidade = new Frm_elasticidade();
         frm_elasticidade.setVisible(true);
         this.dispose();
    }//GEN-LAST:event_btn_ElastMouseClicked

    private void btn_ElastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ElastActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_ElastActionPerformed

    private void btn_ElastCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ElastCMouseClicked
        // TODO add your handling code here:
         Frm_elasticidadecruzada frm_elasticidadecruzada = new Frm_elasticidadecruzada();
         frm_elasticidadecruzada.setVisible(true);
         this.dispose();
    }//GEN-LAST:event_btn_ElastCMouseClicked

    private void btn_ElastCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ElastCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_ElastCActionPerformed

    private void btn_ElastPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ElastPMouseClicked
        // TODO add your handling code here:
         Frm_elasticidadepreco frm_elasticidadepreco = new Frm_elasticidadepreco();
         frm_elasticidadepreco.setVisible(true);
         this.dispose();
    }//GEN-LAST:event_btn_ElastPMouseClicked

    private void btn_ElastPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ElastPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_ElastPActionPerformed

    private void btn_demandaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_demandaActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btn_demandaActionPerformed

    private void btn_demandaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_demandaMouseClicked
        // TODO add your handling code here:
        Frm_demanda frm_demanda = new Frm_demanda();
         frm_demanda.setVisible(true);
         this.dispose();
    }//GEN-LAST:event_btn_demandaMouseClicked

    private void btn_ElastRMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ElastRMouseClicked
        // TODO add your handling code here:
        Frm_elasticidaderenda frm_elasticidaderenda = new Frm_elasticidaderenda();
         frm_elasticidaderenda.setVisible(true);
         this.dispose();
    }//GEN-LAST:event_btn_ElastRMouseClicked

    private void btn_ElastRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ElastRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_ElastRActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PaginaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PaginaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PaginaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PaginaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PaginaInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Elast;
    private javax.swing.JButton btn_ElastC;
    private javax.swing.JButton btn_ElastP;
    private javax.swing.JButton btn_ElastR;
    private javax.swing.JButton btn_cambio;
    private javax.swing.JButton btn_demanda;
    private javax.swing.JButton btn_lucro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
}
